GL-MT5000=https://github.com/m0eak/fanchmwrt.git|main|configs/DSF/mt5000.config|targets/mediatek/filogic|glinet_gl-mt5000
JDC-AX6600=https://github.com/m0eak/libwrt.git|main|configs/DSF/jdcax6600.config|targets/qualcommax/ipq60xx|jdcloud_re-cs-02
