# 设备名称=官方目标路径 (Target Path)
# 注意：这里的路径是相对于 BASE_URL/VERSION/ 的完整子路径

x86_64=targets/x86/64
AXT-1800=targets/qualcommax/ipq60xx
GL-MT3600BE=targets/mediatek/filogic
Cudy-TR3000-256MB=targets/mediatek/filogic
Tenda-BE12PRO=targets/mediatek/filogic

# 您可以在这里继续添加新的设备映射
# 例如：MT7981B_ModelA=targets/mediatek/filogic
